Add `Unit` and `CharSequence` convert
square/kotlinpoet pull request #1189
Opened 2021-11-17 08:33 UTC by liujingxing

kotlinpoet version: 1.10.2
Ksp Version: 1.5.31-1.0.0

```java
class Taco {
    public void add(CharSequence seasoning) { }
}
```

returnType
```kotlin
// Returns a KotlinPoet `ClassName` of value `kotlin.Unit`
val kTypeName = addKsFunction.returnType?.toTypeName()

// Returns a JavaPoet `ClassName` of value `kotlin.Unit`
val jTypeName = kTypeName?.toJTypeName()

```

paramType

```kotlin
// Returns a KotlinPoet `ClassName` of value `kotlin.CharSequence`
val kTypeName = seasoningKsValue.type.toTypeName()

// Returns a JavaPoet `ClassName` of value `kotlin.CharSequence`
val jTypeName = kTypeName.toJTypeName()
```

I expect get `void` and `java.lang.CharSequence`

2021-11-17 15:30 UTC, ZacSweers requested changes
I agree with the charsequence interop but not void to unit. Java can use both void and unit so it's not safe to just assume they're convertible.

2021-11-18 09:46 UTC, liujingxing commented
Ok, void to unit, I can do that myself depending on the usage scenario

For example

```
fun KTypeName.toJavaTypeName(boxIfPrimitive: Boolean = false) =
    toJTypeName(boxIfPrimitive).let {
        when {
            it.toString() == "kotlin.Unit" -> JTypeName.VOID
            else -> it
        }
    }
```

2021-11-28 16:29 UTC, ZacSweers commented
Just note we can't proceed with this or until you remove the void handling

2021-12-06 03:33 UTC, ZacSweers approved these changes

2021-12-06 03:38 UTC, merged